### ISSUE TITLE
Normal style for variables instead of italicizing

### ISSUE THREAD

**Issue by themilinda** [tanyogeorgiev/Pastelin#1]
This is great ADS theme. 
Can we have normal styling for variables please? Variables are already having different color so we can visually differentiate variables. Italicizing reduces readability. May please consider.
Thanks again for the theme.

**Comment by tanyogeorgiev** [comment]
Thank you, I'm so happy to hear some feedbacks! Yes, I will make this change ASAP and will inform you!

**Comment by tanyogeorgiev** [comment]
It's already introduced with [Release 1.1.0](https://github.com/tanyogeorgiev/Pastelin/releases/tag/1.1.0).
You can download [.vsix](https://github.com/tanyogeorgiev/Pastelin/releases/download/1.1.0/pastelin-1.1.0.vsix) file and install the theme again.
There is separate theme "Pastelin No Italic" that you can use. Enjoy :)
![Pastelin No Italic](https://user-images.githubusercontent.com/17822617/101064957-3e856800-359d-11eb-8516-89dc0e8d4af0.png)

**Comment by themilinda** [comment]
Huge Thanks. I have changed my VSCode theme too to Pastelin.
