### ISSUE TITLE
No Italic version still makes comments italic

### ISSUE THREAD

**Issue by tgburgin** [tanyogeorgiev/Pastelin#2]
Hi,

Applying the No Italic version still makes all comments (both -- and /* delimited) appear in italics. Is there a way to amend this?

Cheers,
Tom

**Comment by TheAustinG** [comment]
> Hi,
> 
> Applying the No Italic version still makes all comments (both -- and /* delimited) appear in italics. Is there a way to amend this?
> 
> Cheers,
> Tom

For now, what you can do is edit the settings file yourself. 
1. Locate your settings.json file - for Windows, it's under "\AppData\Roaming\azuredatastudio\User"
2. Add the following to the bottom of the settings.json file

```
"editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": "comment",
                "settings": {
                    "fontStyle": ""
                }
            }
        ]
    }
```
That should fix the italicized comments issue.

**Comment by tgburgin** [comment]
Thanks @TheAustinG. I've already resolved it and created a PR (https://github.com/tanyogeorgiev/Pastelin/pull/3) to add in a new version.
